# Copyright (c) 2026 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  version: "1.0"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: fork
      url-base: https://github.com/gregersrygg
    - name: gminn
      url-base: https://github.com/gminn

  projects:
    - name: sdk-nrf
      remote: gminn
      repo-path: sdk-nrf
      path: nrf
      # gminn/upgrade-memfault-1.42.0: memfault-firmware-sdk 1.42.0 with
      # runtime-configurable project keys.
      revision: dad4ae8166767f5bdbe304f025043080259fe144
      import: true

  self:
    path: project
