# Copyright (c) 2026 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  version: "1.0"

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: fork
      url-base: https://github.com/gregersrygg

  projects:
    - name: sdk-nrf
      remote: fork
      repo-path: sdk-nrf
      path: nrf
      revision: ee28a77e225f30ebc2255790a19d06f23b2cb4ce
      import: true

  self:
    path: project
